<?php

namespace MailPoetVendor;

if (!defined('ABSPATH')) exit;


// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInita5b768809b3b04e5a0dc14eba79090c9::getLoader();
